### ISSUE TITLE
Not compatible with mongoid

### ISSUE THREAD

**Issue by theycallmeswift** [n8/cohort_me#3]
I tried using this with my app that uses Mongoid and got the following error:

```
>> CohortMe.analyze(activation_class: Hackathon)
NoMethodError: private method `select' called for Hackathon:Class
    from /Users/theycallmeswift/.rvm/gems/ruby-1.9.3-p194/gems/cohort_me-0.0.1/lib/cohort_me.rb:34:in `analyze'
    from (irb):2
    from /Users/theycallmeswift/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.12/lib/rails/commands/console.rb:47:in `start'
    from /Users/theycallmeswift/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.12/lib/rails/commands/console.rb:8:in `start'
    from /Users/theycallmeswift/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.12/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by n8** [comment]
Ok. Thanks for posting this! I have never used Mongoid. Right now the code definitely assumes ActiveRecord like syntax. But I'd love to support more databases. Definitely welcome patches from anyone more familiar with Mongoid.

**Comment by letz** [comment]
any development regarding Mongoid support?

**Comment by gitChang** [comment]
Does this mean we have to use <code>.all</code> for the meantime?
